# sample-pipeline.yml

AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline For building

Parameters:
  CodePipelineArtifactStoreBucket:
    Type: String
  CodePipelinDeployDevBucket:
    Type: String
  CodePipelinDeployStgBucket:
    Type: String
  GitHubToken:
    Type: String
  GitHubOwner:
    Type: String
  Repository:
    Type: String
  Branch:
    Type: String
    Description: GitHub Branch
  ServiceName:
    Description: Name for the service
    Type: String
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription:
      can contain only alphanumeric characters, spaces, dashes
      and underscores.
  Type:
    Description: Name for the service type mail/app/bastion/cicd
    Type: String
  Env:
    Description: Environment dev/stg/prd
    Type: String
  CodeBuildImage:
    Type: String
    Default: "aws/codebuild/nodejs:7.0.0"
    Description: Image used for CodeBuild project.
  CodePipelineServiceRole:
    Type: String

Resources:
  # CodePipeline
  ProjectPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref CodePipelineArtifactStoreBucket
        Type: S3
      Name: !Sub ${ServiceName}-${Env}-${Type}-${Branch}-pipeline
      RestartExecutionOnUpdate: false
      RoleArn: !Ref CodePipelineServiceRole
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref Repository
                Branch: !Ref Branch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Fn::ImportValue: !Sub ${ServiceName}-${Env}-${Type}-codeBuild
              OutputArtifacts:
                - Name: CodebuildOutput
              RunOrder: 1
        - Name: Deploy-develop
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: !Ref CodePipelinDeployDevBucket
                Extract: true
              RunOrder: 1
              InputArtifacts:
                - Name: CodebuildOutput
        - Name: Deploy-Approval-Dev2stg
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              Configuration:
                # NotificationArn: !Ref ApprovalTopicArn
                ExternalEntityLink: !Sub https://github.com/${GitHubOwner}/${Repository}
                CustomData: Please review the latest change and approve or reject.
              RunOrder: 1
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: !Ref CodePipelinDeployStgBucket
                Extract: true
              RunOrder: 2
              InputArtifacts:
                - Name: CodebuildOutput
