AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline For deploy

Parameters:
  ServiceName:
    Description: Name for the service
    Type: String
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription:
      can contain only alphanumeric characters, spaces, dashes
      and underscores.
  Type:
    Description: Name for the service type mail/app/bastion/cicd
    Type: String
  Env:
    Description: Environment dev/stg/prd
    Type: String
  CodeDeployServiceRole:
    Type: String
    Description: CodeBuild role name
  AutoScalingGroups:
    Type: String
  CodeDeployStage:
    Type: String
  CodeDeployAplication:
    Type: String

Resources:
  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      DeploymentGroupName: !Ref CodeDeployStage
      ApplicationName: !Ref CodeDeployAplication
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      AutoScalingGroups: !Ref AutoScalingGroups
      ServiceRoleArn: !Ref CodeDeployServiceRole
Outputs:
  StackCodeDeployDeploymentGroup:
    Description: The ID of the CodeDeploymentGroup
    Value: !Ref CodeDeployDeploymentGroup
    Export:
      Name: !Sub ${ServiceName}-${Env}-${Type}-${CodeDeployStage}-codeDeploy
