# sample-pipeline.yml

AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline For building

Parameters:
  CodePipelineArtifactStoreBucket:
    Type: String
  Branch:
    Type: String
    Description: GitHub Branch
  ServiceName:
    Description: Name for the service
    Type: String
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription:
      can contain only alphanumeric characters, spaces, dashes
      and underscores.
  Type:
    Description: Name for the service type mail/app/bastion/cicd
    Type: String
  Env:
    Description: Environment dev/stg/prd
    Type: String
  CodeBuildImage:
    Type: String
    Default: "aws/codebuild/nodejs:7.0.0"
    Description: Image used for CodeBuild project.
  CodeBuildServiceRole:
    Type: String
    Description: CodeBuild role name

Resources:
  # CodeBuildProject
  CodeBuildProject:
    Description: Creating AWS CodeBuild project
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub Building stage for ${Branch}.
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: Branch
            Value: !Ref Branch
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
      Name: !Sub ${ServiceName}-${Env}-${Type}-${Branch}-build
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5
      Cache:
        Type: LOCAL
        Modes: # You can specify one or more cache mode,
          - LOCAL_CUSTOM_CACHE
Outputs:
  StackCodeBuild:
    Description: The ID of the codeBuildProject
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub ${ServiceName}-${Env}-${Type}-codeBuild
